"""empty message

Revision ID: dd42a1b6a578
Revises: 590fafb9db61
Create Date: 2019-07-03 15:26:51.466739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd42a1b6a578'
down_revision = '590fafb9db61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('hide_in_search', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'hide_in_search')
    # ### end Alembic commands ###
